### ISSUE TITLE
how to convert the model to XX.mnn.h file

### ISSUE THREAD

**Issue by shenmayufei** [GHLab/HopenetMNNAndroidSample#1]
Thanks for your share ! When I look into the project ,I could not find the model file ,may be convert into the hopenet_lite.mnn.h,can you show that how to get the file .

**Comment by GHLab** [comment]
I changed it to mnn files. Check here https://github.com/GHLab/HopenetMNNAndroidSample/tree/master/app/src/main/assets
Thank you.
